version: "3.3"

services:
  web-one:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php7
    depends_on:
      - db
    volumes:
      - ../web-one:/var/www/html
    ports:
      - 8080:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: jamg
      MYSQL_PASSWORD: jamg
    ports:
      - 3306:3306

  web-two:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php72
    depends_on:
      - db
    volumes:
      - ../web-two:/var/www/html
    ports:
      - 8081:80
