version: "3.3"

services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile

    container_name: php7
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html
    ports:
      - 80:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: jamg
      MYSQL_PASSWORD: jamg
    ports:
      - 3306:3306
